### ISSUE TITLE
Latest version of smocks nuget package 0.4.15 not working

### ISSUE THREAD

**Issue by jeetendrajaiswal** [vanderkleij/Smocks#10]
I downloaded the latest Smocks nuget package 0.4.15 and tried to run the tests.
However, even the existing tests (which were working properly with previous version of smocks) also stopped working and the below error message is displayed.

"An exception of type 'System.NotSupportedException' occurred in Smocks.dll but was not handled in user code

Additional information: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information."

Kindly check and resolve it asap.

Thanks

**Comment by vanderkleij** [comment]
I cannot seem to reproduce this issue. It sounds as if the assemblies appear to be loaded from a network (or otherwise "insecure") location. Nuget should put the assemblies in a "packages" directory in the solution directory, which is typically a secure location. How did you update Smocks to the 0.4.15 version? If you select the "Smocks" assembly reference in visual studio, does its "path" property point to a local directory? Is your solution on a local disk?

Please try to reinstall Smocks by removing the nuget package and any remaining references and installing it using the nuget package manager. If that does not help, create a new solution and test if Smocks works there: this works for me. Updating smocks ("Update-Package Smocks" in the package manager console) from 0.4.5 to 0.4.15 also seems to work correctly.

**Comment by jeetendrajaiswal** [comment]
its working now...thanks :)

**Comment by vanderkleij** [comment]
@jeetendrajaiswal: in case anyone runs into the same problem: what did you do to resolve the issue?

**Comment by omarmeky** [comment]
@jeetendrajaiswal I am experiencing the same issue. I tried adding this to my app.config to no avail:

```
 <runtime>
    <legacyCasPolicy enabled="true" />
    <loadFromRemoteSources enabled="true"/>
  </runtime>
````

Perhaps one or both these properties need to be added in the project? Any other workarounds?

**Comment by jeetendrajaiswal** [comment]
I remove all the existing references added by smocks and then added the smocks through nuget and the issue was resolved.
