### ISSUE TITLE
private functions are unable to setup context correctly, unless same setup is declare within Smock.Run

### ISSUE THREAD

**Issue by HanaKana** [vanderkleij/Smocks#7]
```C#
[Test]
public void Dummy()
{
	Smock.Run(context =>
	{
		PrivateDummySetup(context);
		var date = DateTime.Now;
		var breakAfter = 123;

		//line is required to 'setup' the datetime.now value correctly in the private function
		//leaving commented out will result in no shim for datetime
		//leaving line in will result in private function setup working. even though function is declared after
//                context.Setup(() => DateTime.Now).Returns(new DateTime(2009));
		var date2 = DateTime.Now;
		var breakAfter2 = 123;
	});
}

private void PrivateDummySetup(ISmocksContext context)
{
	context.Setup(() => DateTime.Now).Returns(new DateTime());
	var date = DateTime.Now;
	var breakAfter = 123;
}
```

Note: using a second setup function on datetime.now will return the first setup returning.

**Comment by vanderkleij** [comment]
This is currently by design. Smocks only scans the lambda provided to `Smock.Run` for `Setup` calls (see [how Smocks works](https://github.com/vanderkleij/Smocks/wiki/How-Smocks-works)). As an improvement, it could additionally scan methods in the same assembly that are invoked by this lambda. I'll keep this issue around as a reminder.

For now, please put all `Smock.Run` invocations directly within the lambda body provided to `Smock.Run`.

**Comment by vanderkleij** [comment]
This is now fixed: Smocks follows calls to methods within the same class and scans those for `Setup` calls as well. This way, the setup in the `PrivateDummySetup` method will be detected by Smocks.
